---
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: ${DEFAULT_ZONE:http://localhost:8761/eureka/}
server:
  port: ${PORT:8080}

initCustomers : 1,Faheem,Sensathian,0806050992;2,John,Doe,0897654321;3,Pond,Sudlohr,0886543211
