---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "api-custinfo-1"
  namespace: "default"
  labels:
    app: "api-custinfo-1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "api-custinfo-1"
  template:
    metadata:
      labels:
        app: "api-custinfo-1"
    spec:
      containers:
      - name: "demo-api-custinfo-sha256-1"
        image: "gcr.io/marine-lane-273704/demo-api-custinfo@sha256:1659673985709f3fd6913403317fe502eb7936e5a6874aa2d3c2f01eb559f20f"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "api-custinfo-1-hpa-g7bq"
  namespace: "default"
  labels:
    app: "api-custinfo-1"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "api-custinfo-1"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80

